POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Full Stack Open 2019 by University of Helsinki – React, Redux, Node.js, MongoDB, and GraphQL",
  "author": "Full Stack Open",
  "url": "https://fullstackopen.com",
  "userId": "5de70b5f8a431f4dbca7de90"
}
