POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN6dHhyIiwiaWQiOiI1ZGU3MGI1ZjhhNDMxZjRkYmNhN2RlOTAiLCJpYXQiOjE1NzU3NTAwNjh9.ftJaEThtI9K0sl4ZpAq0OLUrnv_TG5JECH6QpiK4y1I

{
  "title": "Single Page Apps use token authentication",
  "author": "Full Stack Open 2019",
  "url": "https://fullstackopen.com/en/part4/token_authentication"
}